# Generated by Django 4.0.5 on 2023-07-25 04:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_task_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='note',
        ),
    ]
